"""initial schema

Revision ID: 3b3007610119
Revises: 
Create Date: 2026-04-14 15:28:47.910559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3007610119'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_systems',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('deployment_date', sa.String(length=50), nullable=True),
    sa.Column('is_in_eu_market', sa.Boolean(), nullable=True),
    sa.Column('affected_persons', sa.Text(), nullable=True),
    sa.Column('geographic_scope', sa.String(length=255), nullable=True),
    sa.Column('risk_tier', sa.Enum('UNCLASSIFIED', 'UNACCEPTABLE', 'HIGH', 'LIMITED', 'MINIMAL', name='risktier'), nullable=False),
    sa.Column('annex_iii_article', sa.String(length=100), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('regulation_version', sa.String(length=100), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AWAITING_CLASSIFICATION', 'CLASSIFICATION_IN_PROGRESS', 'CLASSIFIED', 'DOCUMENTATION_IN_PROGRESS', 'COMPLIANT', 'NEEDS_REVIEW', name='systemstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_organisation_id'), 'ai_systems', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ai_systems_risk_tier'), 'ai_systems', ['risk_tier'], unique=False)
    op.create_index(op.f('ix_ai_systems_status'), 'ai_systems', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('annex_iv_documents',
    sa.Column('ai_system_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('interview_answers', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('pdf_s3_key', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('regulation_version', sa.String(length=100), nullable=True),
    sa.Column('claude_model_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annex_iv_documents_ai_system_id'), 'annex_iv_documents', ['ai_system_id'], unique=False)
    op.create_index(op.f('ix_annex_iv_documents_organisation_id'), 'annex_iv_documents', ['organisation_id'], unique=False)
    op.create_table('classifications',
    sa.Column('ai_system_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_answers', sa.JSON(), nullable=True),
    sa.Column('risk_tier', sa.String(length=50), nullable=False),
    sa.Column('annex_iii_article', sa.String(length=100), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('classification_method', sa.String(length=50), nullable=False),
    sa.Column('regulation_version', sa.String(length=100), nullable=True),
    sa.Column('claude_model_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_ai_system_id'), 'classifications', ['ai_system_id'], unique=False)
    op.create_index(op.f('ix_classifications_organisation_id'), 'classifications', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_organisation_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_ai_system_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_annex_iv_documents_organisation_id'), table_name='annex_iv_documents')
    op.drop_index(op.f('ix_annex_iv_documents_ai_system_id'), table_name='annex_iv_documents')
    op.drop_table('annex_iv_documents')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_systems_status'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_risk_tier'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_organisation_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
